-- V4__seed_users.sql
-- Seed default users for development/testing
-- Passwords are BCrypt hashed: "password123"

-- BCrypt hash for "password123" (cost factor 10)
-- Generated by Spring Security BCryptPasswordEncoder

INSERT INTO users (email, password, role, created_at, updated_at)
VALUES 
    -- Admin user: admin@starter.com / password123
    ('admin@starter.com', '$2a$10$hSbR1SKjkq5.ulFEt6ajIeAF19OAPcju5oi/1.lbXI.U2M9.mIXt2', 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    -- Regular user: user@starter.com / password123  
    ('user@starter.com', '$2a$10$hSbR1SKjkq5.ulFEt6ajIeAF19OAPcju5oi/1.lbXI.U2M9.mIXt2', 'USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (email) DO NOTHING;

